services:
  mariadb_glovant:
    container_name: mariadb_glovant
    # NOTA: No usamos 'image: mariadb:latest' porque vamos a tirar 
    #       de configuracion del Dockerfile, asi que usamos 'build'.
    build:
      context: ./resources/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: always