services:
  nginx_glovant:
    container_name: nginx_glovant
    env_file: .env
    build:
      context: ./resources
      dockerfile: Dockerfile
    volumes:
      - ./resources:/usr/share/nginx/html
    ports:
      - "${NGINX_LOCAL_PORT}:${NGINX_DOCKER_PORT}"
    restart: always